Repository MarvinJWendt/testza, pull requests merged in 2022-04, with the labels that each got.

#108 fix: correct file perms on nested snapshot dir
  snapshot.go
  snapshot_test.go
Labels: fix

#112 Better output for `AssertNotEqual`
  CHANGELOG.md
  README.md
  assert.go
Labels: feature

#138 Improved output of `AssertZero` and `AssertNotZero`
  README.md
  assert.go
  internal/fail-printer.go
Labels: feature

#141 Display the correct file when an assertion helper is used internally
  README.md
  internal/assertion_helper.go
Labels: fix

#142 Improved output of `AssertLess`
  README.md
  assert.go
Labels: feature

#144 Improved output of `AssertLen`
  README.md
  assert.go
Labels: feature

#143 Improved output of `AssertNotKindOf`
  README.md
  assert.go
Labels: feature

#145 Improved output of `AssertNotContains`
  README.md
  assert.go
Labels: feature

#148 [BREAKING] Renamed `AssertDirExist` to `AssertDirExists`
  README.md
  assert.go
  assert_test.go
  output/fail_assertions_test.go
Labels: breaking, fix

#153 Added `AssertLessOrEqual` and `AssertGreaterOrEqual`
  README.md
  assert.go
  assert_test.go
  go.mod
Labels: feature

#149 Refactored to support generics!
  .github/workflows/ci.yml
  .github/workflows/go.yml
  .github/workflows/golangci.yml.bak
  CONTRIBUTING.md
  README.md
  assert.go
  assert_test.go
  capture.go
  ci/main.go
  configuration_test.go
  fuzz-bools.go
  fuzz-floats64.go
  fuzz-ints.go
  fuzz-strings.go
  fuzz-utils.go
  fuzz_test.go
  go.mod
  go.sum
  internal/assertion_helper.go
  internal/difference.go
  internal/fail-printer.go
  internal/utils.go
  snapshot.go
  snapshot_test.go
  utils.go
Labels: breaking, feature, RELEASE BLOCKER

#158 Added `AssertUnique` and `AssertNotUnique`
  CHANGELOG.md
  README.md
  assert.go
  assert_test.go
  fuzz-utils.go
  fuzz_test.go
Labels: feature

#159 Added `FuzzUtilDistinctSet`
  README.md
  fuzz_test.go
Labels: feature
